name: uml-diagram-editor

x-back-image: &back-image
  image: umldiagrameditor/uml-diagram-editor-api:latest

x-front-image: &front-image
  image: nginx:stable-alpine

x-back-base: &back-base
  <<: *back-image
  env_file:
    - .env
  environment:
    DB__HOST: db

services:
  db:
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  alembic:
    <<: *back-base
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]
  rbac:
    <<: *back-base
    restart: on-failure
    depends_on:
      alembic:
        condition: service_completed_successfully
    command: ["python3", "init.py"]
  api:
    <<: *back-base
    depends_on:
      rbac:
        condition: service_completed_successfully
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  web:
    <<: *front-image
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/var/www/html:ro
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      TZ: Russia/Moscow
      DB_POSTGRES_HOST: proxy_db
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_USER: ${DB__USER}
      DB_POSTGRES_PASSWORD: ${DB__PASSWORD}
      DB_POSTGRES_NAME: proxy
    ports:
      - "80:80"
      - "81:81"
      - "8443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      proxy_db:
        condition: service_healthy
      web:
        condition: service_healthy

  proxy_db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: proxy
    volumes:
      - proxy_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg_data:
  proxy_pgdata:
  npm_data:
  npm_letsencrypt:
