"""initial

Revision ID: 286dbd8b37dd
Revises:
Create Date: 2026-04-02 16:21:32.494072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286dbd8b37dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile',
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_project_user_name')
    )
    op.create_table('window',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('type', sa.Enum('CLASS_DIAGRAM', name='diagramtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_window_project_name')
    )
    op.create_table('class',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_modifier', sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', 'DEFAULT', name='accessmodifier'), nullable=True),
    sa.Column('is_abstract', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('tile_id', sa.Uuid(), nullable=True),
    sa.Column('window_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'name', name='uq_class_window_name')
    )
    op.create_table('interface',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('tile_id', sa.Uuid(), nullable=False),
    sa.Column('window_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'name', name='uq_interface_window_name')
    )
    op.create_table('attribute',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_modifier', sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', 'DEFAULT', name='accessmodifier'), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_static', sa.Boolean(), nullable=False),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_attribute_class_name')
    )
    op.create_table('method',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_modifier', sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', 'DEFAULT', name='accessmodifier'), nullable=True),
    sa.Column('return_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_static', sa.Boolean(), nullable=False),
    sa.Column('is_abstract', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('interface_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(class_id IS NOT NULL AND interface_id IS NULL) OR (class_id IS NULL AND interface_id IS NOT NULL)', name='method_single_parent_check'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_method_class_name'),
    sa.UniqueConstraint('interface_id', 'name', name='uq_method_interface_name')
    )
    op.create_table('relation',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_type', sa.Enum('RELATION', 'ONE', 'MANY', 'ONE_AND_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationtype'), nullable=False),
    sa.Column('end_type', sa.Enum('RELATION', 'ONE', 'MANY', 'ONE_AND_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationtype'), nullable=False),
    sa.Column('start_class_id', sa.Uuid(), nullable=True),
    sa.Column('start_interface_id', sa.Uuid(), nullable=True),
    sa.Column('end_class_id', sa.Uuid(), nullable=True),
    sa.Column('end_interface_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(end_class_id IS NOT NULL AND end_interface_id IS NULL) OR (end_class_id IS NULL AND end_interface_id IS NOT NULL)', name='single_end_entity_check'),
    sa.CheckConstraint('(start_class_id IS NOT NULL AND start_interface_id IS NULL) OR (start_class_id IS NULL AND start_interface_id IS NOT NULL)', name='single_start_entity_check'),
    sa.ForeignKeyConstraint(['end_class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['end_interface_id'], ['interface.id'], ),
    sa.ForeignKeyConstraint(['start_class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['start_interface_id'], ['interface.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'start_class_id', 'start_interface_id', 'end_class_id', 'end_interface_id', name='uq_relation_unique_pair')
    )
    op.create_table('argument',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('method_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_id', 'name', name='uq_argument_method_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('argument')
    op.drop_table('relation')
    op.drop_table('method')
    op.drop_table('attribute')
    op.drop_table('interface')
    op.drop_table('class')
    op.drop_table('window')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('tile')
    # ### end Alembic commands ###
