"""init

Revision ID: 2cd03542fe25
Revises:
Create Date: 2026-03-23 22:48:21.152617

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cd03542fe25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            'email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            'password_hash',
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'window',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'type', sa.Enum('UML', 'SEQUENCE', name='diagramtype'), nullable=False
        ),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'scheme',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('is_imported', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('window_id', sa.Uuid(), nullable=True),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['window_id'],
            ['window.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tile',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=False),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('width', sa.Integer(), nullable=False),
        sa.Column('pos_x', sa.Integer(), nullable=False),
        sa.Column('pos_y', sa.Integer(), nullable=False),
        sa.Column('window_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['window_id'],
            ['window.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'class',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'access_modifier',
            sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', name='accessmodifier'),
            nullable=False,
        ),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('tile_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tile_id'],
            ['tile.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'interface',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('tile_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tile_id'],
            ['tile.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'attribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            'access_modifier',
            sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', name='accessmodifier'),
            nullable=False,
        ),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('is_final', sa.Boolean(), nullable=False),
        sa.Column('is_static', sa.Boolean(), nullable=False),
        sa.Column('class_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['class_id'],
            ['class.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'method',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            'access_modifier',
            sa.Enum('PUBLIC', 'PRIVATE', 'PROTECTED', name='accessmodifier'),
            nullable=False,
        ),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('is_final', sa.Boolean(), nullable=False),
        sa.Column('is_static', sa.Boolean(), nullable=False),
        sa.Column('class_id', sa.Uuid(), nullable=True),
        sa.Column('interface_id', sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            '(class_id IS NOT NULL AND interface_id IS NULL) OR (class_id IS NULL AND interface_id IS NOT NULL)',
            name='single_parent_check',
        ),
        sa.ForeignKeyConstraint(
            ['class_id'],
            ['class.id'],
        ),
        sa.ForeignKeyConstraint(
            ['interface_id'],
            ['interface.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'relation',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            'start_type',
            sa.Enum(
                'RELATION',
                'ONE',
                'MANY',
                'ONE_AND_ONLY_ONE',
                'ZERO_OR_ONE',
                'ONE_OR_MANY',
                'ZERO_OR_MANY',
                name='relationtype',
            ),
            nullable=False,
        ),
        sa.Column(
            'end_type',
            sa.Enum(
                'RELATION',
                'ONE',
                'MANY',
                'ONE_AND_ONLY_ONE',
                'ZERO_OR_ONE',
                'ONE_OR_MANY',
                'ZERO_OR_MANY',
                name='relationtype',
            ),
            nullable=False,
        ),
        sa.Column('start_class_id', sa.Uuid(), nullable=True),
        sa.Column('start_interface_id', sa.Uuid(), nullable=True),
        sa.Column('end_class_id', sa.Uuid(), nullable=True),
        sa.Column('end_interface_id', sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            '(end_class_id IS NOT NULL AND end_interface_id IS NULL) OR (end_class_id IS NULL AND end_interface_id IS NOT NULL)',
            name='single_end_entity_check',
        ),
        sa.CheckConstraint(
            '(start_class_id IS NOT NULL AND start_interface_id IS NULL) OR (start_class_id IS NULL AND start_interface_id IS NOT NULL)',
            name='single_start_entity_check',
        ),
        sa.ForeignKeyConstraint(
            ['end_class_id'],
            ['class.id'],
        ),
        sa.ForeignKeyConstraint(
            ['end_interface_id'],
            ['interface.id'],
        ),
        sa.ForeignKeyConstraint(
            ['start_class_id'],
            ['class.id'],
        ),
        sa.ForeignKeyConstraint(
            ['start_interface_id'],
            ['interface.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'argument',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('method_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['method_id'],
            ['method.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('argument')
    op.drop_table('relation')
    op.drop_table('method')
    op.drop_table('attribute')
    op.drop_table('interface')
    op.drop_table('class')
    op.drop_table('tile')
    op.drop_table('scheme')
    op.drop_table('window')
    op.drop_table('user')
    # ### end Alembic commands ###
