"""empty message

Revision ID: 484e679e5ee5
Revises: 5acfd26f4ce5
Create Date: 2026-03-31 22:04:19.422832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '484e679e5ee5'
down_revision: Union[str, Sequence[str], None] = '5acfd26f4ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_argument_method_name', 'argument', ['method_id', 'name'])
    op.create_unique_constraint('uq_attribute_class_name', 'attribute', ['class_id', 'name'])
    op.create_unique_constraint('uq_class_window_name', 'class', ['window_id', 'name'])
    op.create_unique_constraint('uq_interface_window_name', 'interface', ['window_id', 'name'])
    op.create_unique_constraint('uq_method_class_name', 'method', ['class_id', 'name'])
    op.create_unique_constraint('uq_method_interface_name', 'method', ['interface_id', 'name'])
    op.create_unique_constraint('uq_project_user_name', 'project', ['user_id', 'name'])
    op.create_unique_constraint('uq_relation_unique_pair', 'relation', ['window_id', 'start_class_id', 'start_interface_id', 'end_class_id', 'end_interface_id'])
    op.create_unique_constraint('uq_window_project_name', 'window', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_window_project_name', 'window', type_='unique')
    op.drop_constraint('uq_relation_unique_pair', 'relation', type_='unique')
    op.drop_constraint('uq_project_user_name', 'project', type_='unique')
    op.drop_constraint('uq_method_interface_name', 'method', type_='unique')
    op.drop_constraint('uq_method_class_name', 'method', type_='unique')
    op.drop_constraint('uq_interface_window_name', 'interface', type_='unique')
    op.drop_constraint('uq_class_window_name', 'class', type_='unique')
    op.drop_constraint('uq_attribute_class_name', 'attribute', type_='unique')
    op.drop_constraint('uq_argument_method_name', 'argument', type_='unique')
    # ### end Alembic commands ###
