"""new

Revision ID: 5acfd26f4ce5
Revises: 841138072c0b
Create Date: 2026-03-30 17:33:01.822018

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5acfd26f4ce5'
down_revision: Union[str, Sequence[str], None] = '841138072c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation', 'start_entity_type')
    op.drop_column('relation', 'end_entity_type')
    op.drop_column('relation', 'start_id')
    op.drop_column('relation', 'end_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation', sa.Column('end_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('relation', sa.Column('start_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('relation', sa.Column('end_entity_type', postgresql.ENUM('CLASS', 'INTERFACE', name='entitytype'), autoincrement=False, nullable=False))
    op.add_column('relation', sa.Column('start_entity_type', postgresql.ENUM('CLASS', 'INTERFACE', name='entitytype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
