"""update relations schema

Revision ID: 5caee34e6cf9
Revises: 8f15a8f134bc
Create Date: 2026-04-18 00:20:05.976588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5caee34e6cf9'
down_revision: Union[str, Sequence[str], None] = '8f15a8f134bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation', sa.Column('type', sa.Enum('RELATION', 'REALIZATION', name='relationkind'), nullable=False))
    op.add_column('relation', sa.Column('begin_type', sa.Enum('RELATION', 'ONE', 'MANY', 'ONE_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationendtype'), nullable=False))
    op.add_column('relation', sa.Column('begin_class_id', sa.Uuid(), nullable=True))
    op.add_column('relation', sa.Column('begin_interface_id', sa.Uuid(), nullable=True))
    op.alter_column('relation', 'end_type',
               existing_type=postgresql.ENUM('RELATION', 'ONE', 'MANY', 'ONE_AND_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationtype'),
               type_=sa.Enum('RELATION', 'ONE', 'MANY', 'ONE_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationendtype'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_relation_unique_pair'), 'relation', type_='unique')
    op.create_unique_constraint('uq_relation_unique_pair', 'relation', ['window_id', 'begin_class_id', 'begin_interface_id', 'end_class_id', 'end_interface_id'])
    op.drop_constraint(op.f('relation_start_class_id_fkey'), 'relation', type_='foreignkey')
    op.drop_constraint(op.f('relation_start_interface_id_fkey'), 'relation', type_='foreignkey')
    op.create_foreign_key(None, 'relation', 'interface', ['begin_interface_id'], ['id'])
    op.create_foreign_key(None, 'relation', 'class', ['begin_class_id'], ['id'])
    op.drop_column('relation', 'start_class_id')
    op.drop_column('relation', 'start_type')
    op.drop_column('relation', 'start_interface_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation', sa.Column('start_interface_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('relation', sa.Column('start_type', postgresql.ENUM('RELATION', 'ONE', 'MANY', 'ONE_AND_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationtype'), autoincrement=False, nullable=False))
    op.add_column('relation', sa.Column('start_class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'relation', type_='foreignkey')
    op.drop_constraint(None, 'relation', type_='foreignkey')
    op.create_foreign_key(op.f('relation_start_interface_id_fkey'), 'relation', 'interface', ['start_interface_id'], ['id'])
    op.create_foreign_key(op.f('relation_start_class_id_fkey'), 'relation', 'class', ['start_class_id'], ['id'])
    op.drop_constraint('uq_relation_unique_pair', 'relation', type_='unique')
    op.create_unique_constraint(op.f('uq_relation_unique_pair'), 'relation', ['window_id', 'start_class_id', 'start_interface_id', 'end_class_id', 'end_interface_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('relation', 'end_type',
               existing_type=sa.Enum('RELATION', 'ONE', 'MANY', 'ONE_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationendtype'),
               type_=postgresql.ENUM('RELATION', 'ONE', 'MANY', 'ONE_AND_ONLY_ONE', 'ONE_OR_MANY', 'ZERO_OR_ONE', 'ZERO_OR_MANY', name='relationtype'),
               existing_nullable=False)
    op.drop_column('relation', 'begin_interface_id')
    op.drop_column('relation', 'begin_class_id')
    op.drop_column('relation', 'begin_type')
    op.drop_column('relation', 'type')
    # ### end Alembic commands ###
