"""empty message

Revision ID: 670f589693ba
Revises: 286dbd8b37dd
Create Date: 2026-04-03 17:28:59.676289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '670f589693ba'
down_revision: Union[str, Sequence[str], None] = '286dbd8b37dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('window', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('window', sa.Column('type', postgresql.ENUM('CLASS_DIAGRAM', name='diagramtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
