"""add constraints to methods

Revision ID: 9d93fe22555e
Revises: f11767e98c64
Create Date: 2026-05-12 19:02:01.768580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d93fe22555e'
down_revision: Union[str, Sequence[str], None] = 'f11767e98c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE relation ALTER COLUMN type SET DEFAULT 'RELATION';")
    op.execute("UPDATE relation SET type = 'RELATION'::relationkind WHERE type IS NULL;")
    op.execute("ALTER TABLE relation ALTER COLUMN type SET NOT NULL;")
    op.create_check_constraint('final_abstract_conflict', 'method', 'NOT (is_final = TRUE AND is_abstract = TRUE)')
    op.create_check_constraint(
        'static_abstract_conflict',
        'method',
        'NOT (is_static = TRUE AND is_abstract = TRUE)'
    )
    op.create_check_constraint(
        'interface_method_constraints',
        'method',
        """
        (interface_id IS NULL) OR (
        interface_id IS NOT NULL AND
        (access_modifier = 'PUBLIC' OR access_modifier IS NULL)
        AND is_final = FALSE
        AND is_static = FALSE
        )
        """
    )
    op.create_check_constraint(
        'abstract_class_method_rules',
        'method',
        """
        (class_id IS NULL OR is_abstract = FALSE) OR (
        class_id IS NOT NULL AND is_abstract = TRUE
        AND access_modifier IN ('PUBLIC', 'PROTECTED', NULL)
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE relation Alter COLUMN type DROP not null;")
    # ### end Alembic commands ###
    op.drop_constraint('final_abstract_conflict', 'method')
    op.drop_constraint('static_abstract_conflict', 'method')
    op.drop_constraint('interface_method_constraints', 'method')
    op.drop_constraint('abstract_class_method_rules', 'method')
